queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Semantic Pull Request
      - "#approved-reviews-by>=1"
      - -title~=(WIP|wip)
      - -label~="do-not-merge"
      - "#changes-requested-reviews-by=0"

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
#       - check-success=build  # matrix jobs aren't working in mergify
    actions:
      queue:
        method: squash
        commit_message: title+body

  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - base!=master
#       - check-success=build  # matrix jobs aren't working in mergify
      - "#approved-reviews-by>=2"
    actions:
      queue:
        method: squash
        strict_method: merge
        commit_message: title+body
