image:
  file: .gitpod.Dockerfile
tasks:
  - init: make dev-gitpod
vscode:
  extensions:
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - ms-azuretools.vscode-docker
    - davidanson.vscode-markdownlint
    - bungcip.better-toml
