Resources:
  AwsLambdaPowertoolsPythonLayer:
      Type: AWS::Serverless::Application
      Properties:
          Location:
              ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
              SemanticVersion: 2.0.0 # change to latest semantic version available in SAR

  MyLambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
          Layers:
              # fetch Layer ARN from SAR App stack output
              - !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn