# Standalone workflow to update changelog if necessary
name: Build changelog

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  changelog:
    uses: ./.github/workflows/reusable_publish_changelog.yml
