# Standalone workflow to update changelog if necessary
name: Build changelog

on:
  schedule:
    - cron: 0,30 * * * *

jobs:
  changelog:
    uses: ./.github/workflows/reusable_publish_changelog.yml
