# Standalone workflow to update changelog if necessary
name: Build changelog

on:
  workflow_dispatch:

jobs:
  changelog:
    needs: release
    uses: ./.github/workflows/reusable_publish_changelog.yml
