name: Docs

on:
  push:
    branches:
      - develop
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "examples/**"
      - "CHANGELOG.md"

permissions:
  id-token: write

jobs:
  release-docs:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: ./.github/workflows/reusable_publish_docs.yml
    with:
      version: develop
      alias: stage
    secrets:
      AWS_DOCS_ROLE_ARN: ${{ secrets.AWS_DOCS_ROLE_ARN }}
      AWS_DOCS_BUCKET: ${{ secrets.AWS_DOCS_BUCKET }}