name: Monthly roadmap reminder

on:
    workflow_dispatch: {}
#   schedule:
#     - cron: '0 0 1 * *'

permissions:
    contents: read
    pull-requests: read
    issues: read


jobs:
    call-workflow-passing-data:
        uses: aws-powertools/actions/.github/workflows/monthly_roadmap_reminder.yml@main
        with:
            token: ${{ github.token }}


