name: Monthly roadmap reminder

on:
    workflow_dispatch: {}
#   schedule:
#     - cron: '0 0 1 * *'

permissions:
    contents: read


jobs:
    call-workflow-passing-data:
        permissions:
            contents: read
            pull-requests: read
            issues: write  # create monthly roadmap report
        uses: aws-powertools/actions/.github/workflows/monthly_roadmap_reminder.yml@main
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
