# Run fuzzing against changes in Pull Requests for bug and leaks detection
name: Continuous Fuzzing (ClusterFuzzLite)

# PROCESS
#
# 1. Build a fuzzer for python for each sanitizer
# 2. Fuzz each sanitizer against entire repository
# 3. Aggregate results and upload report as an artifact

# NOTES
#
# More info: https://google.github.io/clusterfuzzlite/

on:
  schedule:
    - cron: '0 0/6 * * *'  # Every 6th hour.

permissions: read-all

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
        - address    # memory safety issues
        - undefined  # undefined behaviour (e.g., integer workflows, dangling pointers)
        - memory     # uninitialized memory (e.g., C-extensions)
    steps:
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@1e163f06cba7820da5154ac9fe1a32d7fe6f73a3  # v1
      with:
        language: python
        sanitizer: ${{ matrix.sanitizer }}
    - name: Run Fuzzers (${{ matrix.sanitizer }})
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@1e163f06cba7820da5154ac9fe1a32d7fe6f73a3  # v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 3600
        mode: 'batch'
        sanitizer: ${{ matrix.sanitizer }}
