name: Monthly roadmap reminder

on:
    workflow_dispatch: {}
    schedule:
      - cron: '0 0 1 * *'  # runs first day of the month

permissions:
    contents: read


jobs:
    call-workflow-passing-data:
        permissions:
            contents: read
            pull-requests: read
            issues: write  # create monthly roadmap report

        # setting to `@main` until we have releases and governance installed
        uses: aws-powertools/actions/.github/workflows/monthly_roadmap_reminder.yml@main
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
