name: Deploy v2 layer to all regions

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      latest_published_version:
        description: "Latest PyPi published version to rebuild latest docs for, e.g. v1.22.0"
        required: true

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "hello world"
