name: Docs

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feat/docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Build docs website
        run: make docs
      # - name: DEBUG tmate session
      #   uses: mxschmitt/action-tmate@v2
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
