name: Docs

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feat/docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Build docs website
        uses: jzweifel/gatsby-cli-github-action@v1.0.0
        env:
          GATSBY_PROJECT_PATH: "./docs"
        with:
          gatsby-arg: build
      - name: Build API docs
        run: make docs-api
      - name: deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
