name: Rebuild latest docs

#
# === Documentation hotfix ===
#
# 1. Trigger "Rebuild latest docs" workflow manually: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
# 2. Use the latest version released under Releases e.g. 2.0.0

on:
  schedule:
    - cron: 0,30 * * * *

jobs:
  changelog:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable_publish_changelog.yml

  release-docs:
    needs: changelog
    permissions:
      contents: write
      pages: write
    uses: ./.github/workflows/reusable_publish_docs.yml
    with:
      version: ${{ inputs.latest_published_version }}
      alias: latest
