name: Build and publish latest changelog

on:
  workflow_call:

jobs:
  publish_changelog:
    # Force Github action to run only a single job at a time (based on the group name)
    # This is to prevent race-condition and inconsistencies with changelog push
    concurrency:
      group: changelog-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository # reusable workflows start clean, so we need to checkout again
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
        with:
          fetch-depth: 0
      - name: "Generate latest changelog"
        run: make changelog
      - name: Create PR
        uses: ./.github/actions/create-pr
        with:
          files: "CHANGELOG.md"
          temp_branch_prefix: "ci-changelog"
          pull_request_title: "chore(ci): changelog rebuild"
          github_token: ${{ secrets.GITHUB_TOKEN }}
