name: Deploy V2 SAR

permissions:
  id-token: write
  contents: read

env:
  SAM_VERSION: 2.44.0
  NODE_VERSION: 16.12
  AWS_REGION: eu-west-1
  SAR_NAME: aws-lambda-powertools-python-layer-v2

on:
  workflow_call:
    inputs:
      stage:
        description: "Deployment stage (BETA, PROD)"
        required: true
        type: string
      artefact-name:
        description: "CDK Layer Artefact name to download"
        required: true
        type: string
      package-version:
        description: "The version of the package to deploy"
        required: true
        type: string
      environment:
        description: "GitHub Environment to use for encrypted secrets"
        required: true
        type: string

jobs:
  deploy-sar-app:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_LAYERS_ROLE_ARN }}
      - name: AWS credentials SAR role
        uses: aws-actions/configure-aws-credentials@v1
        id: aws-credentials-sar-role
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          role-duration-seconds: 1200
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_SAR_V2_ROLE_ARN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact-name }}
      - name: Unzip artefact
        run: |
          unzip cdk.out.zip
      - name: Set test SAR name
        run: |
          NAME=${{ env.SAR_NAME }}
          if [[ "${{ inputs.stage }}" == "BETA" ]]; then
            NAME="test-$NAME"
          fi
          echo SAR_NAME="${NAME}" >> "$GITHUB_ENV"
      - name: Deploy x86_64 SAR
        run: |
          asset=$(jq -jc '.Resources[] | select(.Properties.CompatibleArchitectures == ["x86_64"]) | .Metadata."aws:asset:path"' cdk.out/LayerV2Stack.template.json)
          sed -e "s|<VERSION>|${{ inputs.package-version }}|g" -e "s/<SAR_APP_NAME>/${{ env.SAR_NAME }}/g" -e "s|<LAYER_CONTENT_PATH>|./cdk.out/$asset|g" layer/sar/template.txt > template.yml
          cp README.md LICENSE "./cdk.out/$asset/"
          sam package --template-file template.yml --output-template-file packaged.yml --s3-bucket ${{ secrets.AWS_SAR_S3_BUCKET }}
          sam publish --template packaged.yml --region "$AWS_REGION"
      - name: Publish x86_64 SAR
        if: ${{ inputs.stage == 'PROD' }}
        run: |
          # wait until sar registers the app, otherwise it fails to make it public
          sleep 15
          echo "Make x86_64 SAR app public"
          aws serverlessrepo put-application-policy --application-id arn:aws:serverlessrepo:${{ env.AWS_REGION }}:${{ steps.aws-credentials-sar-role.outputs.aws-account-id }}:applications/${{ env.SAR_NAME }} --statements Principals='*',Actions=Deploy
      - name: Deploy arm64 SAR
        run: |
          asset=$(jq -jc '.Resources[] | select(.Properties.CompatibleArchitectures == ["arm64"]) | .Metadata."aws:asset:path"' cdk.out/LayerV2Stack.template.json)
          sed -e "s|<VERSION>|${{ inputs.package-version }}|g" -e "s/<SAR_APP_NAME>/${{ env.SAR_NAME }}-arm64/g" -e "s|<LAYER_CONTENT_PATH>|./cdk.out/$asset|g" layer/sar/template.txt > template.yml
          cp README.md LICENSE "./cdk.out/$asset/"
          sam package --template-file template.yml --output-template-file packaged.yml --s3-bucket ${{ secrets.AWS_SAR_S3_BUCKET }}
          sam publish --template packaged.yml --region "$AWS_REGION"
      - name: Publish arm64 SAR
        if: ${{ inputs.stage == 'PROD' }}
        run: |
          # wait until sar registers the app, otherwise it fails to make it public
          sleep 15
          echo "Make arm64 SAR app public"
          aws serverlessrepo put-application-policy --application-id arn:aws:serverlessrepo:${{ env.AWS_REGION }}:${{ steps.aws-credentials-sar-role.outputs.aws-account-id }}:applications/${{ env.SAR_NAME }}-arm64 --statements Principals='*',Actions=Deploy
      - name: Deploy BETA canary
        if: ${{ inputs.stage == 'BETA' }}
        run: |
          STACK_NAME=serverlessrepo-v2-powertools-layer-test-stack

          echo "Check if stack does not exist"
          stack_exists=$(aws cloudformation list-stacks --query "StackSummaries[?(StackName == '$STACK_NAME' && StackStatus == 'CREATE_COMPLETE')].{StackId:StackId, StackName:StackName, CreationTime:CreationTime, StackStatus:StackStatus}" --output text)
          echo "$stack_exists"
          if [[ -n "$stack_exists" ]] ; then
            echo "Found test deployment stack, removing..."
            aws cloudformation delete-stack --stack-name "$STACK_NAME"
            aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
          fi

          echo "Creating canary stack"
          echo "Stack name: $STACK_NAME"
          aws serverlessrepo create-cloud-formation-change-set --application-id arn:aws:serverlessrepo:${{ env.AWS_REGION }}:${{ steps.aws-credentials-sar-role.outputs.aws-account-id }}:applications/${{ env.SAR_NAME }} --stack-name "${STACK_NAME/serverlessrepo-/}" --capabilities CAPABILITY_NAMED_IAM
          CHANGE_SET_ID=$(aws cloudformation list-change-sets --stack-name "$STACK_NAME" --query 'Summaries[*].ChangeSetId' --output text)
          aws cloudformation wait change-set-create-complete --change-set-name "$CHANGE_SET_ID"
          aws cloudformation execute-change-set --change-set-name "$CHANGE_SET_ID"
          aws cloudformation wait stack-create-complete --stack-name "$STACK_NAME"
          echo "Waiting until stack deployment completes..."

          echo "Exit with error if stack is not in CREATE_COMPLETE"
          stack_exists=$(aws cloudformation list-stacks --query "StackSummaries[?(StackName == '$STACK_NAME' && StackStatus == 'CREATE_COMPLETE')].{StackId:StackId, StackName:StackName, CreationTime:CreationTime, StackStatus:StackStatus}")
          if [[ -z "$stack_exists" ]] ; then
            echo "Could find successful deployment, exit error..."
            exit 1
          fi
          echo "Deployment successful"
      - name: Cleanup BETA x86_64 SAR
        if: ${{ inputs.stage == 'BETA' }}
        run: |
          app_id=$(aws serverlessrepo list-applications --output text --query "Applications[?ApplicationId=='arn:aws:serverlessrepo:${{ env.AWS_REGION }}:${{ steps.aws-credentials-sar-role.outputs.aws-account-id }}:applications/${{ env.SAR_NAME }}'].ApplicationId")
          if [ -z "${app_id}" ]; then
            echo "Could not find the SAR that we just deployed."
          fi
          aws serverlessrepo delete-application --application-id "$app_id"
      - name: Cleanup BETA arm64 SAR
        if: ${{ inputs.stage == 'BETA' }}
        run: |
          app_id=$(aws serverlessrepo list-applications --output text --query "Applications[?ApplicationId=='arn:aws:serverlessrepo:${{ env.AWS_REGION }}:${{ steps.aws-credentials-sar-role.outputs.aws-account-id }}:applications/${{ env.SAR_NAME }}-arm64'].ApplicationId")
          if [ -z "${app_id}" ]; then
            echo "Could not find the SAR that we just deployed."
          fi
          aws serverlessrepo delete-application --application-id "$app_id"
