name: Run end-to-end tests

on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened]
    paths:
      - "aws_lambda_powertools/**"
      - "tests/e2e/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mypy.ini"
      - "parallel_run_e2e.py"
      - "README.md"
# Maintenance: Add support for triggering on `run-e2e` label
# and enforce repo origin to prevent abuse

env:
  AWS_DEFAULT_REGION: us-east-1
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.me
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.me
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to request JWT with GitHub's OIDC Token endpoint. docs: https://bit.ly/3MNgQO9
      contents: read
      actions: read
    strategy:
      matrix:
        version: ["3.7", "3.8", "3.9"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.APIKEY_LAB }}
      - name: Install poetry
        run: pipx install poetry
      - name: "Use Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          architecture: "x64"
          cache: "poetry"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.12"
      - name: Install CDK CLI
        run: |
          npm install
          npx cdk --version
      - name: Install dependencies
        run: make dev
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_TEST_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Test
        run: make e2e-test
      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.APIKEY_LAB }}
          test_format: JUNIT
          test_framework: PYTEST
          test_path: ./results/**
