name: Lockdown untrusted workflows

on:  
  schedule:
    - cron: '*/30 * * * *'

jobs:
  enforce_pinned_workflows:
    name: Harden Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.APIKEY_LAB }}
      - name: Ensure 3rd party workflows have SHA pinned
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@6ca5574367befbc9efdb2fa25978084159c5902d # v1.3.0
        with:
          # Trusted GitHub Actions and/or organizations
          allowlist: |
            aws-actions/
            actions/checkout
            actions/github-script
            actions/setup-node
            actions/setup-python
            actions/upload-artifact
            actions/download-artifact
            github/codeql-action/init
            github/codeql-action/analyze
            dependabot/fetch-metadata
